import { Resend } from 'resend';
function client(){if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM)return null;return new Resend(process.env.RESEND_API_KEY)}
function manageUrl(baseUrl,registration){return `${baseUrl}/manage.html?token=${encodeURIComponent(registration.editToken)}`}
const copy={
 en:{title:'FEDUSA Congress Registration',received:'Registration received successfully',updated:'Registration updated',reference:'Registration reference',affiliate:'Affiliate',attendees:'Registered attendees',delegate:'Delegate',instruction:'Use the secure button below to review or amend the existing registration.',manageAffiliate:'Manage Affiliate Registration',manageMine:'Manage My Registration',privacy:'Keep this link private. It provides access to edit this registration.',subjectReceived:'Your FEDUSA Congress Registration has been received',subjectAffiliate:'Your FEDUSA Affiliate Registration has been received',subjectUpdated:'Your FEDUSA Congress registration has been updated',linkTitle:'Your secure management link',linkSubject:'Your FEDUSA Congress management link',noRequest:'If you did not request this email, no action is required.'},
 af:{title:'FEDUSA Kongresregistrasie',received:'Registrasie suksesvol ontvang',updated:'Registrasie opgedateer',reference:'Registrasieverwysing',affiliate:'Geaffilieerde organisasie',attendees:'Geregistreerde deelnemers',delegate:'Afgevaardigde',instruction:'Gebruik die veilige knoppie hieronder om die bestaande registrasie te hersien of te wysig.',manageAffiliate:'Bestuur geaffilieerde registrasie',manageMine:'Bestuur my registrasie',privacy:'Hou hierdie skakel privaat. Dit bied toegang om die registrasie te wysig.',subjectReceived:'Jou FEDUSA-kongresregistrasie is ontvang',subjectAffiliate:'Jou FEDUSA-geaffilieerde registrasie is ontvang',subjectUpdated:'Jou FEDUSA-kongresregistrasie is opgedateer',linkTitle:'Jou veilige bestuurskakel',linkSubject:'Jou FEDUSA-kongresbestuurskakel',noRequest:'Geen optrede is nodig indien jy nie hierdie e-pos versoek het nie.'},
 fr:{title:'Inscription au congrès FEDUSA',received:'Inscription reçue avec succès',updated:'Inscription mise à jour',reference:'Référence de l’inscription',affiliate:'Affilié',attendees:'Participants inscrits',delegate:'Délégué',instruction:'Utilisez le bouton sécurisé ci-dessous pour consulter ou modifier l’inscription existante.',manageAffiliate:'Gérer l’inscription affiliée',manageMine:'Gérer mon inscription',privacy:'Gardez ce lien confidentiel. Il permet de modifier cette inscription.',subjectReceived:'Votre inscription au congrès FEDUSA a été reçue',subjectAffiliate:'Votre inscription affiliée FEDUSA a été reçue',subjectUpdated:'Votre inscription au congrès FEDUSA a été mise à jour',linkTitle:'Votre lien de gestion sécurisé',linkSubject:'Votre lien de gestion du congrès FEDUSA',noRequest:'Si vous n’avez pas demandé cet e-mail, aucune action n’est requise.'},
 pt:{title:'Inscrição no Congresso FEDUSA',received:'Inscrição recebida com sucesso',updated:'Inscrição atualizada',reference:'Referência da inscrição',affiliate:'Afiliado',attendees:'Participantes inscritos',delegate:'Delegado',instruction:'Utilize o botão seguro abaixo para consultar ou alterar a inscrição existente.',manageAffiliate:'Gerir inscrição de afiliado',manageMine:'Gerir a minha inscrição',privacy:'Mantenha este link privado. Permite editar esta inscrição.',subjectReceived:'A sua inscrição no Congresso FEDUSA foi recebida',subjectAffiliate:'A sua inscrição de afiliado FEDUSA foi recebida',subjectUpdated:'A sua inscrição no Congresso FEDUSA foi atualizada',linkTitle:'A sua ligação segura de gestão',linkSubject:'A sua ligação de gestão do Congresso FEDUSA',noRequest:'Se não solicitou este e-mail, não é necessária qualquer ação.'},
 es:{title:'Inscripción al Congreso FEDUSA',received:'Inscripción recibida correctamente',updated:'Inscripción actualizada',reference:'Referencia de inscripción',affiliate:'Afiliado',attendees:'Asistentes inscritos',delegate:'Delegado',instruction:'Utilice el botón seguro de abajo para revisar o modificar la inscripción existente.',manageAffiliate:'Gestionar inscripción de afiliado',manageMine:'Gestionar mi inscripción',privacy:'Mantenga este enlace privado. Permite editar esta inscripción.',subjectReceived:'Hemos recibido su inscripción al Congreso FEDUSA',subjectAffiliate:'Hemos recibido su inscripción de afiliado FEDUSA',subjectUpdated:'Su inscripción al Congreso FEDUSA ha sido actualizada',linkTitle:'Su enlace seguro de gestión',linkSubject:'Su enlace de gestión del Congreso FEDUSA',noRequest:'Si no solicitó este correo, no es necesario realizar ninguna acción.'}
};
function languageCopy(registration){return copy[registration.language]||copy.en}
function shell(c,body){return `<div style="font-family:Arial,sans-serif;color:#102043;max-width:650px;margin:auto"><div style="background:#08275c;padding:24px;color:white"><h1 style="margin:0">${c.title}</h1></div><div style="padding:28px;border:1px solid #dce3ed">${body}</div></div>`}
export async function sendConfirmation({to,registration,baseUrl,updated=false}){
 const resend=client();if(!resend)return {skipped:true};const affiliate=registration.registrationType==='affiliate',url=manageUrl(baseUrl,registration),c=languageCopy(registration);
 const subject=updated?c.subjectUpdated:affiliate?c.subjectAffiliate:c.subjectReceived;
 const names=(registration.delegateIds||[]).map((id,i)=>registration.delegateNames?.[i]||id).join(', ');
 const html=shell(c,`<h2>${updated?c.updated:c.received}</h2><p>${c.reference}: <strong>${registration.registrationId}</strong></p>${affiliate?`<p>${c.affiliate}: <strong>${registration.affiliate}</strong></p><p>${c.attendees}: ${names}</p>`:`<p>${c.delegate}: <strong>${names}</strong></p>`}<p>${c.instruction}</p><p><a href="${url}" style="display:inline-block;background:#20a651;color:white;padding:13px 20px;text-decoration:none;border-radius:7px;font-weight:bold">${affiliate?c.manageAffiliate:c.manageMine}</a></p><p style="font-size:12px;color:#667085">${c.privacy}</p>`);
 return resend.emails.send({from:process.env.EMAIL_FROM,to:[to],subject,html});
}
export async function sendManageLink({to,registration,baseUrl}){
 const resend=client();if(!resend)return {skipped:true};const affiliate=registration.registrationType==='affiliate',url=manageUrl(baseUrl,registration),c=languageCopy(registration);
 return resend.emails.send({from:process.env.EMAIL_FROM,to:[to],subject:c.linkSubject,html:shell(c,`<h2>${c.linkTitle}</h2><p>${c.reference}: <strong>${registration.registrationId}</strong></p><p><a href="${url}" style="display:inline-block;background:#20a651;color:white;padding:13px 20px;text-decoration:none;border-radius:7px;font-weight:bold">${affiliate?c.manageAffiliate:c.manageMine}</a></p><p style="font-size:12px;color:#667085">${c.noRequest}</p>`)});
}
