import {json,requireAdmin,recordsStore,appendAudit,now,assertNoHardDuplicate,normalizeEmail,normalizeMobile} from './_shared.js';
import {sendConfirmation,sendAdminNotification} from './_email.js';
function same(a,b){return JSON.stringify(a??null)===JSON.stringify(b??null)}
export default async(req)=>{if(req.method!=='PUT')return json({error:'Method not allowed'},405);try{const b=await req.json();requireAdmin(b.pin);const store=recordsStore(),d=await store.get(`delegate/${b.delegateId}`,{type:'json'});if(!d)return json({error:'Delegate not found'},404);
 const proposed={...d,...(b.changes||{})};await assertNoHardDuplicate(proposed,{excludeDelegateIds:[d.delegateId]});const changes=[];
 for(const k of ['fullName','jobTitle','email','mobile','dietary','accessibility','shirtJacketSize','votingMember','accommodation','conferenceDates','inboundFlight','outboundFlight'])if(b.changes?.[k]!==undefined){if(!same(d[k],b.changes[k]))changes.push(`${d.fullName}: ${k} updated`);d[k]=b.changes[k];}d.normalizedEmail=normalizeEmail(d.email);d.normalizedMobile=normalizeMobile(d.mobile);d.updatedAt=now();await store.setJSON(`delegate/${d.delegateId}`,d);
 const reg=await store.get(`registration/${d.registrationId}`,{type:'json'});if(reg){if(reg.registrationType==='main')reg.ownerEmail=d.email;reg.delegateNames=(reg.delegateNames||[]).map((n,i)=>reg.delegateIds[i]===d.delegateId?d.fullName:n);reg.updatedAt=now();reg.status='Updated';await store.setJSON(`registration/${reg.registrationId}`,reg);}
 await appendAudit({registrationId:d.registrationId,delegateId:d.delegateId,actor:'Admin',action:'Delegate record updated',details:{fields:Object.keys(b.changes||{}),changes}});
 if(reg){const baseUrl=process.env.SITE_URL||new URL(req.url).origin;try{await sendConfirmation({to:reg.ownerEmail,registration:reg,baseUrl,updated:true,changes});}catch(e){console.error('Delegate admin-update email error',e)}try{await sendAdminNotification({type:'updated',registration:reg,baseUrl,changes,actor:'Admin'});}catch(e){console.error('Admin update notification error',e)}}return json({ok:true,delegate:d})}catch(e){return json({error:e.message},e.code==='DUPLICATE_DELEGATE'?409:401)}};
